# Generated by Django 5.1.5 on 2025-06-07 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_auth', '0002_role_address_permission_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='permission',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_permissions', to='contenttypes.contenttype'),
        ),
    ]
