# Generated by Django 5.1.1 on 2025-05-13 09:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_cartitem_variant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
        migrations.RenameField(
            model_name='variantattribute',
            old_name='attribute_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='variantattribute',
            old_name='attribute_value',
            new_name='value',
        ),
        migrations.AlterUniqueTogether(
            name='variantattribute',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('template', 'Template'), ('product', 'Product'), ('variant', 'Variant')], default='product', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='product',
            field=models.ForeignKey(default=datetime.datetime(2025, 5, 13, 9, 37, 42, 989758, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='variant_attributes', to='ecommerce.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_title', models.CharField(max_length=255)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(max_length=255)),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('personal', 'Personal'), ('billing', 'Billing'), ('shipping', 'Shipping'), ('warehouse', 'Warehouse'), ('store', 'Store'), ('shop', 'Shop'), ('other', 'Other')], default='home', max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='variantattribute',
            name='variant',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
