# Generated by Django 5.1.1 on 2025-05-13 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_remove_productprice_variant_remove_cartitem_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ecommerce.product'),
        ),
    ]
