# Generated by Django 5.1.1 on 2025-05-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_rename_name_variantattribute_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='valid_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
