# Generated by Django 5.1.5 on 2025-06-21 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_alter_orderitem_amount_alter_orderitem_price_and_more'),
        ('user_auth', '0005_user_dob_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_auth.address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
